server:
  port: 8000

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://web-study.c6csxmxkinkd.ap-northeast-2.rds.amazonaws.com:3306/back-20220829
    username: admin
    password: 1q2w3e4r

servlet:
  multipart:
    max-file-size: 100MB
    max-request-size: 100MB

mybatis:
  mapper-locations:
    - /mappers/*.xml


file:
  path: C:/mingyeong/web/springboot/springboot-mvc-20220916-min/upload/